In [1]:
import numpy as np
import cv2 as cv

In [2]:
def decTObin(num):
    bnum = bin(num).replace("0b", "")
    return "0"*(8-len(bnum))+bnum

In [12]:
img = cv.imread(r"C:\Users\Charith Janaka\Desktop\Sem_05\CSD\Processor_Design\Repository\ImageProcessing\Lena256X256.png",cv.IMREAD_GRAYSCALE)

imgpaded = cv.copyMakeBorder(img, 1, 1, 1, 1, cv.BORDER_CONSTANT,None, value = 0)

print(imgpaded.shape)

filew = open("Lena256X256_DRAM.txt","w")
imgf = open("Lena256X256pixels.txt","w")
W, H = imgpaded.shape

for x in range (W):
    for y in range (H):
        filew.write(str((decTObin(imgpaded[x][y])))+"\n")
        imgf.write(str((imgpaded[x][y]))+" "+(y==257)*"\n")

(258, 258)


In [9]:
kh = np.array([1/4,1/2,1/4], np.float32)
kv = np.array([1/4,1/2,1/4], np.float32)

vc_img = open("verticalconv256x256.txt","w")
lpf_img = open("lpf256x256.txt","w")
ds_img = open("ds256x256.txt","w")

# Vertical Convolution
W1 = 258
H1 = 256

imgres = np.zeros((258,258),np.uint8)

for x in range(W1):
    for y in range(H1):
        tot1 = imgpaded[y][x]*kv[0] + imgpaded[y+1][x]*kv[1] + imgpaded[y+2][x]*kv[2]
        vc_img.write(str(int(tot1))+ " "+ (y==257)*"\n")
        imgres[y+1][x] = int(tot1)

#print(imgres)

imglpf = np.zeros((256,256),np.uint8)

#Horizontal Convolution

W2 = 256
H2 = 256

for x in range(W2):
    for y in range(H2):
        tot = imgres[x+1][y]*kh[0] + imgres[x+1][y+1]*kh[1] + imgres[x+1][y+2]*kh[2]
        imglpf[x][y] = int(tot)
        lpf_img.write(str(int(tot))+ " "+ (y==255)*"\n")

#print("\n")

#print(imglpf)

imgds = np.zeros((128,128),np.uint8)

#Downsampling
W3 = 128
H3 = 128
i = 0

for x in range(W3):
    j = 0
    for y in range(H3):
        imgds[x][y] = imglpf[i][j]
        ds_img.write(str(int(imglpf[i][j]))+ " "+ (y==127)*"\n")
        j+= 2
    i+= 2

#print(imgds)

[[ 90 118 119 ...  88 116 118]
 [119 158 159 ... 122 131 109]
 [117 155 155 ... 111  67  46]
 ...
 [ 39  54  60 ...  56  52  59]
 [ 36  51  56 ...  57  65  82]
 [ 34  47  52 ...  60  82  99]]
