In [ ]:
import cv2 as cv
import numpy as np

In [ ]:
def decTObin(num):
    bnum = bin(num).replace("0b", "")
    return "0"*(8-len(bnum))+bnum

In [ ]:
img = cv.imread(r"C:\Users\Charith Janaka\Desktop\Sem_05\CSD\Processor_Design\Repository\ImageProcessing\Lena128x128.png",cv.IMREAD_GRAYSCALE)
imgpaded = cv.copyMakeBorder(img, 1, 1, 1, 1, cv.BORDER_CONSTANT,None, value = 0)
print(imgpaded.shape)
pixels = open("pixels.txt","w")

W, H = imgpaded.shape

for x in range (W):
    for y in range (H):
        pixels.write(str((imgpaded[x][y]))+" "+"\n"*(y==129))

In [ ]:
kh = np.array([1/4,1/2,1/4], np.float32)
kv = np.array([1/4,1/2,1/4], np.float32)

lpf_img = open("lpf_img.txt","w")

imgres = np.zeros((130,130),np.uint8)

#Horizontal Convolution
W0, H0 = imgpaded.shape
W0 = W0 - 2
H0 = H0 - 2

for x in range(W0):
    for y in range(H0):
        tot = imgpaded[x][y]*kh[0] + imgpaded[x][y+1]*kv[1] + imgpaded[x][y+2]*kv[2]
        imgres[x][y+1] = int(tot)

print(imgres)

# Vertical Convolution
W1,H1 = imgpaded.shape
W1 = W1-2
H1 = H1-2

for x in range(W1):
    for y in range(H1):
        tot1 = imgres[y][x+1]*kv[0] + imgres[y+1][x+1]*kv[1] + imgres[y+2][x+1]*kv[2]
        lpf_img.write(str(int(tot1))+ " "+ (y==127)*"\n")
        imgres[y+1][x+1] = int(tot1)

print(imgres)


In [15]:
import numpy as np
import cv2 as cv

img = np.array([[101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],
                [101,102,103,104,105,106,107,108,109,110],])

imgp = cv.copyMakeBorder(img, 1, 1, 1, 1, cv.BORDER_CONSTANT,None, value = 0)

pixels = open("img10x10.txt","w")

W, H = imgp.shape

for x in range (W):
    for y in range (H):
        pixels.write(str((imgp[x][y]))+" "+"\n"*(y==11))

In [17]:
def decTObin(num):
    bnum = bin(num).replace("0b", "")
    return "0"*(8-len(bnum))+bnum

pixelsd = open("img10x10ram.txt","w")

W, H = imgp.shape

for x in range (W):
    for y in range (H):
        pixelsd.write(str((decTObin(imgp[x][y])))+"\n")

In [27]:
kh = np.array([1/4,1/2,1/4], np.float32)
kv = np.array([1/4,1/2,1/4], np.float32)

vc_img = open("verticalconv10x10.txt","w")

# Vertical Convolution
W1 = 12
H1 = 10

imgres = np.zeros((12,12),np.uint8)

for x in range(W1):
    for y in range(H1):
        tot1 = imgp[y][x]*kv[0] + imgp[y+1][x]*kv[1] + imgp[y+2][x]*kv[2]
        #vc_img.write(str(int(tot1))+ " "+ (y==11)*"\n")
        imgres[y+1][x] = int(tot1)

print(imgres)

imglpf = np.zeros((10,10),np.uint8)

#Horizontal Convolution

W2 = 10
H2 = 10

for x in range(W2):
    for y in range(H2):
        tot = imgres[x+1][y]*kh[0] + imgres[x+1][y+1]*kh[1] + imgres[x+1][y+2]*kh[2]
        imglpf[x][y] = int(tot)

print("\n")

print(imglpf)

[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  75  76  77  78  78  79  80  81  81  82   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0  75  76  77  78  78  79  80  81  81  82   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]]


[[ 56  76  77  77  78  79  80  80  81  61]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82]
 [ 76 102 103 104 105 106 107 108 109  82

In [29]:
imghc = np.zeros((12,12),np.uint8)

kh = np.array([1/4,1/2,1/4], np.float32)

#Horizontal Convolution

W2 = 12
H2 = 10

for x in range(W2):
    for y in range(H2):
        tot = imgp[x][y]*kh[0] + imgp[x][y+1]*kh[1] + imgp[x][y+2]*kh[2]
        imghc[x][y+1] = int(tot)
print(imgp)
print("\n")
print(imghc)

[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0 101 102 103 104 105 106 107 108 109 110   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]]


[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 106 107 108 109  82   0]
 [  0  76 102 103 104 105 10